# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'PracaInzynierska-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PracaInzynierska-iOS
  pod 'Alamofire'
  pod 'Toast-Swift', '~> 5.0.0'
  pod 'SDWebImage', '~> 5.0'
  
end
